{
  "Header": {
    "Original": "CVE-2025-30714 (Vulnerability in the MySQL Connectors product of Oracle MySQL (compone ...)",
    "ID": "CVE-2025-30714",
    "Description": "(Vulnerability in the MySQL Connectors product of Oracle MySQL (compone ...)"
  },
  "Annotations": [
    {
      "Original": "- mysql-connector-python 9.3.0-1 (bug #1103396)",
      "Type": "package",
      "Package": "mysql-connector-python",
      "Kind": "fixed",
      "Version": "9.3.0-1",
      "BugNo": 1103396
    },
    {
      "Original": "NOTE: https://security.snyk.io/vuln/SNYK-PYTHON-MYSQLCONNECTORPYTHON-9724724",
      "Type": "NOTE",
      "Description": "https://security.snyk.io/vuln/SNYK-PYTHON-MYSQLCONNECTORPYTHON-9724724"
    },
    {
      "Original": "NOTE: https://github.com/mysql/mysql-connector-python/commit/68a6b5157838d1a2eea0b52d5542ac3e7ebaaa8f (9.3.0)",
      "Type": "NOTE",
      "Description": "https://github.com/mysql/mysql-connector-python/commit/68a6b5157838d1a2eea0b52d5542ac3e7ebaaa8f (9.3.0)"
    }
  ]
}