{
  "Header": {
    "Original": "CVE-2025-8194 (There is a defect in the CPython \\u201ctarfile\\u201d module affecting  ...)",
    "ID": "CVE-2025-8194",
    "Description": "(There is a defect in the CPython \\u201ctarfile\\u201d module affecting  ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 3.13.6-1",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "fixed",
      "Version": "3.13.6-1"
    },
    {
      "Original": "- python3.12 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "removed"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python3.9 \u003cpostponed\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python3.9",
      "Kind": "postponed",
      "Description": "Minor issue"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed"
    },
    {
      "Original": "[bullseye] - python2.7 \u003cend-of-life\u003e (EOL in bullseye LTS)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python2.7",
      "Kind": "end-of-life",
      "Description": "EOL in bullseye LTS"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/130577",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/130577"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/137027",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/137027"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/ZULLF3IZ726XP5EY7XJ7YIN3K5MDYR2D/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/ZULLF3IZ726XP5EY7XJ7YIN3K5MDYR2D/"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/7040aa54f14676938970e10c5f74ea93cd56aa38 (main)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/7040aa54f14676938970e10c5f74ea93cd56aa38 (main)"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/python/cpython/commit/cdae923ffe187d6ef916c0f665a31249619193fe (3.13-branch)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/python/cpython/commit/cdae923ffe187d6ef916c0f665a31249619193fe (3.13-branch)"
    }
  ]
}