{
  "Header": {
    "Original": "CVE-2025-32911 (A use-after-free type vulnerability was found in libsoup, in the soup_ ...)",
    "ID": "CVE-2025-32911",
    "Description": "(A use-after-free type vulnerability was found in libsoup, in the soup_ ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-4140-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-4140-1"
      ]
    },
    {
      "Original": "- libsoup3 3.6.4-1",
      "Type": "package",
      "Package": "libsoup3",
      "Kind": "fixed",
      "Version": "3.6.4-1"
    },
    {
      "Original": "[bookworm] - libsoup3 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "- libsoup2.4 2.74.3-10.1 (bug #1103515)",
      "Type": "package",
      "Package": "libsoup2.4",
      "Kind": "fixed",
      "Version": "2.74.3-10.1",
      "BugNo": 1103515
    },
    {
      "Original": "[bookworm] - libsoup2.4 \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "libsoup2.4",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/issues/433",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/issues/433"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/422",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/libsoup/-/merge_requests/422"
    },
    {
      "Original": "NOTE: Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/f4a761fb66512fff59798765e8ac5b9e57dceef0 (3.6.2)",
      "Type": "NOTE",
      "Description": "Fixed by: https://gitlab.gnome.org/GNOME/libsoup/-/commit/f4a761fb66512fff59798765e8ac5b9e57dceef0 (3.6.2)"
    }
  ]
}