{
  "Header": {
    "Original": "CVE-2025-45768 (pyjwt v2.10.1 was discovered to contain weak encryption.)",
    "ID": "CVE-2025-45768",
    "Description": "(pyjwt v2.10.1 was discovered to contain weak encryption.)"
  },
  "Annotations": [
    {
      "Original": "- pyjwt \u003cunfixed\u003e (bug #1110318)",
      "Type": "package",
      "Package": "pyjwt",
      "Kind": "unfixed",
      "BugNo": 1110318
    },
    {
      "Original": "NOTE: disputed upstream",
      "Type": "NOTE",
      "Description": "disputed upstream"
    },
    {
      "Original": "NOTE: The \"insufficient key length\" seems to refer to the fact that pyjwt does not enforce that a key",
      "Type": "NOTE",
      "Description": "The \"insufficient key length\" seems to refer to the fact that pyjwt does not enforce that a key"
    },
    {
      "Original": "NOTE: Generating a key of insufficient length for the purpose you want to use it for is a user problem.",
      "Type": "NOTE",
      "Description": "Generating a key of insufficient length for the purpose you want to use it for is a user problem."
    },
    {
      "Original": "NOTE: A library may not decide that my key length is insufficient, as it has no way to determine what the goal of my token is.",
      "Type": "NOTE",
      "Description": "A library may not decide that my key length is insufficient, as it has no way to determine what the goal of my token is."
    },
    {
      "Original": "NOTE: https://github.com/jpadilla/pyjwt/issues/1080",
      "Type": "NOTE",
      "Description": "https://github.com/jpadilla/pyjwt/issues/1080"
    },
    {
      "Original": "NOTE: https://github.com/advisories/GHSA-xpf8-484v-j9w6",
      "Type": "NOTE",
      "Description": "https://github.com/advisories/GHSA-xpf8-484v-j9w6"
    },
    {
      "Original": "NOTE: https://github.com/jpadilla/pyjwt/security/advisories/GHSA-72ff-rqxp-4hrh",
      "Type": "NOTE",
      "Description": "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-72ff-rqxp-4hrh"
    }
  ]
}