{
  "Header": {
    "Original": "CVE-2025-3155 (A flaw was found in Yelp. The Gnome user help application allows the h ...)",
    "ID": "CVE-2025-3155",
    "Description": "(A flaw was found in Yelp. The Gnome user help application allows the h ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5927-1 DLA-4185-1 DLA-4184-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5927-1",
        "DLA-4185-1",
        "DLA-4184-1"
      ]
    },
    {
      "Original": "- yelp 42.2-3 (bug #1102080)",
      "Type": "package",
      "Package": "yelp",
      "Kind": "fixed",
      "Version": "42.2-3",
      "BugNo": 1102080
    },
    {
      "Original": "- yelp-xsl 42.1-4",
      "Type": "package",
      "Package": "yelp-xsl",
      "Kind": "fixed",
      "Version": "42.1-4"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2357091",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2357091"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2025/04/04/1",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2025/04/04/1"
    },
    {
      "Original": "NOTE: https://gitlab.gnome.org/GNOME/yelp/-/issues/221",
      "Type": "NOTE",
      "Description": "https://gitlab.gnome.org/GNOME/yelp/-/issues/221"
    },
    {
      "Original": "NOTE: https://blogs.gnome.org/mcatanzaro/2025/04/15/dangerous-arbitrary-file-read-vulnerability-in-yelp-cve-2025-3155/",
      "Type": "NOTE",
      "Description": "https://blogs.gnome.org/mcatanzaro/2025/04/15/dangerous-arbitrary-file-read-vulnerability-in-yelp-cve-2025-3155/"
    },
    {
      "Original": "NOTE: https://gist.github.com/parrot409/e970b155358d45b298d7024edd9b17f2",
      "Type": "NOTE",
      "Description": "https://gist.github.com/parrot409/e970b155358d45b298d7024edd9b17f2"
    }
  ]
}